---
- hosts: localhost
  connection: local
  gather_facts: no

  # vars_files:
  #   - "vars/fromTerraform.yml"
  #   - "vars/creds.json"

  # vars:
  #   listVsName: []
  #   listPoolName: []
  #   listVsVip: []

  roles:
    - role: "avinetworks.avisdk"

  tasks:

    - name: Debug
      debug:
        msg: "{{ avi_credentials }}"
      tags:
        - debug


    - name: Get GSLB list
      avi_api_session:
        avi_credentials: "{{ avi_credentials }}"
        api_version: "{{ avi_credentials.api_version }}"
        http_method: get
        path: gslbservice
      register: gslbserviceResults

    - name: Debug
      debug:
        msg: "{{ item.name }}"
      loop: "{{ gslbserviceResults.obj.results }}"
      tags:
        - debug

    - name: Delete GSLB service (dns)
      avi_gslbservice:
        avi_credentials: "{{ avi_credentials }}"
        api_version: "{{ avi_credentials.api_version }}"
        name: "{{ item.name }}"
        state: absent
        tenant_ref: "/api/tenant?name={{ item.tenant_ref | default('admin') }}"
        tenant: "{{ item.tenant_ref | default('admin') }}"
      loop: "{{ gslbserviceResults.obj.results }}"
      loop_control:
        label: "{{ item.name }}"

    - name: get VS
      avi_api_session:
        avi_credentials: "{{ avi_credentials }}"
        api_version: "{{ avi_credentials.api_version }}"
        http_method: get
        timeout: 300
        path: virtualservice
      register: virtualserviceResults
      tags:
        - debug

    - name: Debug
      debug:
        msg: "{{ item.name }}"
      loop: "{{ virtualserviceResults.obj.results }}"
      tags:
        - debug

    - name: Delete Virtualservice
      avi_virtualservice:
        avi_credentials: "{{ avi_credentials }}"
        api_version: "{{ avi_credentials.api_version }}"
        name: "{{ item.name }}"
        state: absent
        cloud_ref: "/api/cloud/?name={{ avi_cloud.name }}"
        tenant_ref: "/api/tenant?name={{ item.tenant_ref | default('admin') }}"
        tenant: "{{ item.tenant_ref | default('admin') }}"
      loop: "{{ virtualserviceResults.obj.results }}"
      loop_control:
        label: "{{ item.name }}"


    - name: get vsvip
      avi_api_session:
        avi_credentials: "{{ avi_credentials }}"
        api_version: "{{ avi_credentials.api_version }}"
        http_method: get
        timeout: 300
        path: vsvip
      register: vsvipResults
      tags:
        - debug

    - name: Debug
      debug:
        msg: "{{ item.name }}"
      loop: "{{ vsvipResults.obj.results }}"
      tags:
        - debug

    - name: Delete VsVip
      avi_vsvip:
        avi_credentials: "{{ avi_credentials }}"
        api_version: "{{ avi_credentials.api_version }}"
        name: "{{ item.name }}"
        state: absent
        cloud_ref: "/api/cloud/?name={{ avi_cloud.name }}"
        tenant_ref: "/api/tenant?name={{ item.tenant_ref | default('admin') }}"
        tenant: "{{ item.tenant_ref | default('admin') }}"
      loop: "{{ vsvipResults.obj.results }}"
      loop_control:
        label: "{{ item.name }}"

    - name: get pools
      avi_api_session:
        avi_credentials: "{{ avi_credentials }}"
        api_version: "{{ avi_credentials.api_version }}"
        http_method: get
        timeout: 300
        path: pool
      register: poolResults

    - name: Delete pool
      avi_pool:
        avi_credentials: "{{ avi_credentials }}"
        api_version: "{{ avi_credentials.api_version }}"
        name: "{{ item.name }}"
        cloud_ref: "/api/cloud/?name={{ avi_cloud.name }}"
        tenant: "{{ item.tenant_ref | default('admin') }}"
        tenant_ref: "/api/tenant?name={{ item.tenant_ref | default('admin') }}"
        state: absent
      loop: "{{ poolResults.obj.results }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Get SE list
      avi_api_session:
        avi_credentials: "{{ avi_credentials }}"
        api_version: "{{ avi_credentials.api_version }}"
        http_method: get
        path: serviceengine
      register: serviceengineResults

    - name: Debug
      debug:
        msg: "{{ item.name }}"
      loop: "{{ serviceengineResults.obj.results }}"
      tags:
        - debug

    - name: Delete All SEs
      avi_serviceengine:
        avi_credentials: "{{ avi_credentials }}"
        api_version: "{{ avi_credentials.api_version }}"
        name: "{{ item.name }}"
        state: absent
      loop: "{{ serviceengineResults.obj.results }}"
      loop_control:
        label: "{{ item.name }}"

    - name: Pausing for 120 seconds
      pause:
        minutes: 2

    - name: Get SE group list
      avi_api_session:
        avi_credentials: "{{ avi_credentials }}"
        api_version: "{{ avi_credentials.api_version }}"
        http_method: get
        path: serviceenginegroup
      register: serviceenginegroupResults

    - name: Debug
      debug:
        msg: "{{ item.name }}"
      loop: "{{ serviceenginegroupResults.obj.results }}"
      tags:
        - debug

    - name: Delete se group (except Default Group)
      avi_serviceenginegroup:
        cloud_ref: "/api/cloud/?name={{ avi_cloud.name }}"
        avi_credentials: "{{ avi_credentials }}"
        api_version: "{{ avi_credentials.api_version }}"
        name: "{{ item.name }}"
        state: absent
      loop: "{{ serviceenginegroupResults.obj.results }}"
      loop_control:
        label: "Modifying SE group called {{ item.name }}"
      when: item.name != "Default-Group"

    - name: Pausing for 20 seconds
      pause:
        seconds: 20

    - name: Delete Avi Cloud
      avi_cloud:
        avi_credentials: "{{ avi_credentials }}"
        api_version: "{{ avi_credentials.api_version }}"
        name: "{{ avi_cloud.name }}"
        state: absent
        vtype: "{{ avi_cloud.vtype }}"
      when: avi_cloud is defined
      tags: cloud
      ignore_errors: yes
