---
- hosts: localhost
  connection: local
  gather_facts: no

  # vars_files:
  #   - "vars/fromTerraform.yml"
  #   - "vars/creds.json"

  vars:
    listVsName: []
    listPoolName: []
    listVsVip: []

  roles:
    - role: "avinetworks.avisdk"

  tasks:

    - name: Debug
      debug:
        msg: "{{ avi_credentials }}"
      tags:
        - debug

    - name: Debug
      debug:
        msg: "{{ avi_cloud.name }}"
      tags:
        - debug

    - name: Get GSLB list
      avi_api_session:
        avi_credentials: "{{ avi_credentials }}"
        api_version: "{{ avi_credentials.api_version }}"
        http_method: get
        path: gslbservice
      register: gslbserviceResults

    # - name: Debug
    #   debug:
    #     msg: "{{ item.name }}"
    #   loop: "{{ gslbserviceResults.obj.results }}"
    #   tags:
    #     - debug
    #
    # - name: Debug
    #   debug:
    #     msg: "{{ item.uuid }}"
    #   loop: "{{ gslbserviceResults.obj.results }}"
    #   tags:
    #     - debug

    - name: "Delete Glsb services"
      avi_api_session:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        http_method: "delete"
        path: '{{"gslbservice/" + item.uuid }}'
      loop: "{{ gslbserviceResults.obj.results }}"

    - name: Get GSLB list
      avi_api_session:
        avi_credentials: "{{ avi_credentials }}"
        api_version: "{{ avi_credentials.api_version }}"
        http_method: get
        path: gslbgeodbprofile
      register: gslbgeodbprofileResults

    - name: "Delete Glsb Geo profile"
      avi_api_session:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        http_method: "delete"
        path: '{{"gslbgeodbprofile/" + item.uuid }}'
      loop: "{{ gslbgeodbprofileResults.obj.results }}"

    - name: Get GSLB config
      avi_api_session:
        avi_credentials: "{{ avi_credentials }}"
        api_version: "{{ avi_credentials.api_version }}"
        http_method: get
        path: gslb
      register: gslbResults

    - name: "Delete Glsb config"
      avi_api_session:
        avi_credentials: "{{ avi_credentials | default(omit) }}"
        http_method: "delete"
        path: '{{"gslb/" + item.uuid }}'
      loop: "{{ gslbResults.obj.results }}"
