---
- hosts: localhost
  connection: local
  gather_facts: no

  # vars_files:
  #   - "vars/fromTerraform.yml"
  #   - "vars/creds.json"

  vars:
    listVsName: []
    listPoolName: []
    listVsVip: []

  roles:
    - role: "avinetworks.avisdk"

  tasks:

    - name: Debug
      debug:
        msg: "{{ avi_credentials }}"
      tags:
        - debug

    - name: Debug
      debug:
        msg: "{{ avi_cloud.name }}"
      tags:
        - debug

    - name: Get GSLB list
      avi_api_session:
        avi_credentials: "{{ avi_credentials }}"
        api_version: "{{ avi_credentials.api_version }}"
        http_method: get
        path: gslbservice
      register: gslbserviceResults

    - name: Debug
      debug:
        msg: "{{ item.name }}"
      loop: "{{ gslbserviceResults.obj.results }}"
      tags:
        - debug

    - name: Debug
      debug:
        msg: "{{ item.uuid }}"
      loop: "{{ gslbserviceResults.obj.results }}"
      tags:
        - debug

    - name: Delete GSLB service (dns)
      avi_gslbservice:
        avi_credentials: "{{ avi_credentials }}"
        api_version: "{{ avi_credentials.api_version }}"
        name: "{{ item.name }}"
        uuid: "{{ item.uuid }}"
        state: absent
        tenant_ref: "/api/tenant?name={{ item.tenant_ref | default('admin') }}"
        tenant: "{{ item.tenant_ref | default('admin') }}"
      loop: "{{ gslbserviceResults.obj.results }}"
      loop_control:
        label: "{{ item.name }}"
